trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - hotfix/*
  paths:
    include:
      - 'src/**'

pr:
  branches:
    include:
      - main
      - develop
      - feature/*
      - hotfix/*
  paths:
    include:
      - 'src/**'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest tests/
  displayName: 'Run tests'

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
    wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
    unzip terraform_1.0.11_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: 'Install Terraform'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
